<a href="https://colab.research.google.com/github/cobaltsleet49/VibeCheck/blob/main/Copy_of_ML_Group11_LoanPrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# please feel free to make changes as you please
from huggingface_hub import hf_hub_download
from sklearn.linear_model import LogisticRegression
from imblearn.over_sampling import SMOTE
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import (AdaBoostClassifier, GradientBoostingClassifier, RandomForestClassifier, StackingClassifier)
from sklearn.metrics import (accuracy_score, confusion_matrix, ConfusionMatrixDisplay, f1_score, precision_recall_curve, precision_score, recall_score)
from sklearn.preprocessing import (OneHotEncode, LabelEncoder, StandardScaler)
from sklearn.model_selection import (train_test_split, GridSearchCV)

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)

In [ ]:
# this cell takes a while to run watch out
csv_path = hf_hub_download(
    repo_id="beedubb/hdmaLARdata",
    filename="2025_public_lar_csv.csv",
    repo_type="dataset",
)

# 10% sampling
df = pd.read_csv(
    csv_path,
    skiprows=lambda i: i > 0 and np.random.rand() > 0.1, # change this float, 0.1 = 10%, 0.2=20% and so on
    low_memory=False,
)

print(f"Successfully loaded shape: {df.shape}")

Successfully loaded shape: (1354928, 99)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1354928 entries, 0 to 1354927
Data columns (total 99 columns):
 #   Column                                    Non-Null Count    Dtype
---  ------                                    --------------    -----
 0   activity_year                             1354928 non-null  int64
 1   lei                                       1354928 non-null  object
 2   derived_msa_md                            1354928 non-null  int64
 3   state_code                                1337779 non-null  object
 4   county_code                               1324665 non-null  float64
 5   census_tract                              1319109 non-null  object
 6   conforming_loan_limit                     1349240 non-null  object
 7   derived_loan_product_type                 1354928 non-null  object
 8   derived_dwelling_category                 1354928 non-null  object
 9   derived_ethnicity                         1354928 non-null  object
 10  derived_race                              1354928 non-null  object
 11  derived_sex                               1354928 non-null  object
 12  action_taken                              1354928 non-null  int64
 13  purchaser_type                            1354928 non-null  int64
 14  preapproval                               1354928 non-null  int64
 15  loan_type                                 1354928 non-null  int64
 16  loan_purpose                              1354928 non-null  int64
 17  lien_status                               1354928 non-null  int64
 18  reverse_mortgage                          1354928 non-null  int64
 19  open_end_line_of_credit                   1354928 non-null  int64
 20  business_or_commercial_purpose            1354928 non-null  int64
 21  loan_amount                               1354928 non-null  int64
 22  combined_loan_to_value_ratio              883254 non-null   object
 23  interest_rate                             901049 non-null   object
 24  rate_spread                               672489 non-null   object
 25  hoepa_status                              1354928 non-null  int64
 26  total_loan_costs                          645452 non-null   object
 27  total_points_and_fees                     40217 non-null    object
 28  origination_charges                       652429 non-null   object
 29  discount_points                           340396 non-null   object
 30  lender_credits                            235854 non-null   object
 31  loan_term                                 1338901 non-null  object
 32  prepayment_penalty_term                   72868 non-null    object
 33  intro_rate_period                         291548 non-null   object
 34  negative_amortization                     1354928 non-null  int64
 35  interest_only_payment                     1354928 non-null  int64
 36  balloon_payment                           1354928 non-null  int64
 37  other_nonamortizing_features              1354928 non-null  int64
 38  property_value                            1075923 non-null  object
 39  construction_method                       1354928 non-null  int64
 40  occupancy_type                            1354928 non-null  int64
 41  manufactured_home_secured_property_type   1354928 non-null  int64
 42  manufactured_home_land_property_interest  1354928 non-null  int64
 43  total_units                               1354928 non-null  object
 44  multifamily_affordable_units              35452 non-null    object
 45  income                                    1136271 non-null  float64
 46  debt_to_income_ratio                      872203 non-null   object
 47  applicant_credit_score_type               1354928 non-null  int64
 48  co_applicant_credit_score_type            1354928 non-null  int64
 49  applicant_ethnicity_1                     1354485 non-null  float64
 50  applicant_ethnicity_2                     80659 non-null    float64
 51  applicant_ethnicity_3                     1579 non-null     float64
 52  applicant_ethnicity_4                     50 non-null       float64
 53  applicant_ethnicity_5                     26 non-null       float64
 54  co_applicant_ethnicity_1                  1354776 non-null  float64
 55  co_applicant_ethnicity_2                  30176 non-null    float64
 56  co_applicant_ethnicity_3                  549 non-null      float64
 57  co_applicant_ethnicity_4                  16 non-null       float64
 58  co_applicant_ethnicity_5                  11 non-null       float64
 59  applicant_ethnicity_observed              1354928 non-null  int64
 60  co_applicant_ethnicity_observed           1354928 non-null  int64
 61  applicant_race_1                          1354616 non-null  float64
 62  applicant_race_2                          65277 non-null    float64
 63  applicant_race_3                          5434 non-null     float64
 64  applicant_race_4                          835 non-null      float64
 65  applicant_race_5                          308 non-null      float64
 66  co_applicant_race_1                       1354824 non-null  float64
 67  co_applicant_race_2                       25335 non-null    float64
 68  co_applicant_race_3                       1938 non-null     float64
 69  co_applicant_race_4                       282 non-null      float64
 70  co_applicant_race_5                       117 non-null      float64
 71  applicant_race_observed                   1354928 non-null  int64
 72  co_applicant_race_observed                1354928 non-null  int64
 73  applicant_sex                             1354928 non-null  int64
 74  co_applicant_sex                          1354928 non-null  int64
 75  applicant_sex_observed                    1354928 non-null  int64
 76  co_applicant_sex_observed                 1354928 non-null  int64
 77  applicant_age                             1354928 non-null  object
 78  co_applicant_age                          1354928 non-null  object
 79  applicant_age_above_62                    1172364 non-null  object
 80  co_applicant_age_above_62                 477153 non-null   object
 81  submission_of_application                 1354928 non-null  int64
 82  initially_payable_to_institution          1354928 non-null  int64
 83  aus_1                                     1354928 non-null  int64
 84  aus_2                                     73647 non-null    float64
 85  aus_3                                     22553 non-null    float64
 86  aus_4                                     9413 non-null     float64
 87  aus_5                                     8173 non-null     float64
 88  denial_reason_1                           1354928 non-null  int64
 89  denial_reason_2                           47750 non-null    float64
 90  denial_reason_3                           8816 non-null     float64
 91  denial_reason_4                           1727 non-null     float64
 92  tract_population                          1354928 non-null  int64
 93  tract_minority_population_percent         1354928 non-null  float64
 94  ffiec_msa_md_median_family_income         1354928 non-null  int64
 95  tract_to_msa_income_percentage            1354928 non-null  float64
 96  tract_owner_occupied_units                1354928 non-null  int64
 97  tract_one_to_four_family_homes            1354928 non-null  int64
 98  tract_median_age_of_housing_units         1354928 non-null  int64
dtypes: float64(31), int64(40), object(28)
memory usage: 1023.4+ MB

In [ ]:
df.head(10)

,activity_year,lei,derived_msa_md,state_code,county_code,census_tract,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,derived_ethnicity,derived_race,derived_sex,action_taken,purchaser_type,preapproval,loan_type,loan_purpose,lien_status,reverse_mortgage,open_end_line_of_credit,business_or_commercial_purpose,loan_amount,combined_loan_to_value_ratio,interest_rate,rate_spread,hoepa_status,total_loan_costs,total_points_and_fees,origination_charges,discount_points,lender_credits,loan_term,prepayment_penalty_term,intro_rate_period,negative_amortization,interest_only_payment,balloon_payment,other_nonamortizing_features,property_value,construction_method,occupancy_type,manufactured_home_secured_property_type,manufactured_home_land_property_interest,total_units,multifamily_affordable_units,income,debt_to_income_ratio,applicant_credit_score_type,co_applicant_credit_score_type,applicant_ethnicity_1,applicant_ethnicity_2,applicant_ethnicity_3,applicant_ethnicity_4,applicant_ethnicity_5,co_applicant_ethnicity_1,co_applicant_ethnicity_2,co_applicant_ethnicity_3,co_applicant_ethnicity_4,co_applicant_ethnicity_5,applicant_ethnicity_observed,co_applicant_ethnicity_observed,applicant_race_1,applicant_race_2,applicant_race_3,applicant_race_4,applicant_race_5,co_applicant_race_1,co_applicant_race_2,co_applicant_race_3,co_applicant_race_4,co_applicant_race_5,applicant_race_observed,co_applicant_race_observed,applicant_sex,co_applicant_sex,applicant_sex_observed,co_applicant_sex_observed,applicant_age,co_applicant_age,applicant_age_above_62,co_applicant_age_above_62,submission_of_application,initially_payable_to_institution,aus_1,aus_2,aus_3,aus_4,aus_5,denial_reason_1,denial_reason_2,denial_reason_3,denial_reason_4,tract_population,tract_minority_population_percent,ffiec_msa_md_median_family_income,tract_to_msa_income_percentage,tract_owner_occupied_units,tract_one_to_four_family_homes,tract_median_age_of_housing_units
0,2025,549300QFJDBOCX7WKY08,46060,AZ,4019.0,04019004428,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,1,0,2,1,1,1,2,2,1,625000,49.408,7.25,NaN,3,NaN,NaN,NaN,NaN,NaN,60,NaN,NaN,2,2,1,2,1265000,1,2,3,5,1,NaN,NaN,NaN,9,10,4.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,3,4,7.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,3,4,4,5,3,4,8888,9999,NaN,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,3187,26.61,96100,180.0,1599,1765,32
1,2025,549300QFJDBOCX7WKY08,23104,TX,48439.0,48439100900,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,1,0,2,1,31,1,2,2,1,435000,52.575,7,NaN,3,NaN,NaN,NaN,NaN,NaN,120,NaN,60,2,2,1,2,395000,1,3,3,5,2,NaN,NaN,NaN,9,10,4.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,3,4,7.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,3,4,4,5,3,4,8888,9999,NaN,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,1854,94.88,106900,67.0,230,772,0
2,2025,254900Y3KT6SZM11MQ06,34980,TN,47189.0,47189030102,NC,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Male,4,0,2,1,31,1,1111,1111,1111,1415000,Exempt,Exempt,Exempt,3,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,1111,1111,1111,1111,Exempt,1,1,1111,1111,1,Exempt,213.0,Exempt,1111,1111,2.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,4,5.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,2,4,1,5,2,4,55-64,9999,No,NaN,1111,1111,1111,NaN,NaN,NaN,NaN,1111,NaN,NaN,NaN,7100,14.85,112200,91.0,2327,2808,29
3,2025,254900Y3KT6SZM11MQ06,26420,TX,48201.0,48201250602,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,1,0,2,1,1,1,1111,1111,1111,165000,Exempt,Exempt,Exempt,3,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,1111,1111,1111,1111,Exempt,1,3,1111,1111,1,Exempt,NaN,Exempt,1111,1111,4.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,3,4,7.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,3,4,4,5,3,4,8888,9999,NaN,NaN,1111,1111,1111,NaN,NaN,NaN,NaN,1111,NaN,NaN,NaN,4792,77.78,102000,64.0,537,1284,41
4,2025,254900Y3KT6SZM11MQ06,13140,TX,48361.0,48361022302,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,1,0,2,1,2,1,1111,1111,1111,155000,Exempt,Exempt,Exempt,3,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,1111,1111,1111,1111,Exempt,1,3,1111,1111,2,Exempt,NaN,Exempt,1111,1111,4.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,3,4,7.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,3,4,4,5,3,4,8888,9999,NaN,NaN,1111,1111,1111,NaN,NaN,NaN,NaN,1111,NaN,NaN,NaN,3852,14.69,84400,169.0,743,1172,34
5,2025,254900Y3KT6SZM11MQ06,26420,TX,48201.0,48201540101,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Hispanic or Latino,Race Not Available,Joint,1,0,2,1,1,1,1111,1111,1111,615000,Exempt,Exempt,Exempt,2,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,1111,1111,1111,1111,Exempt,1,1,1111,1111,1,Exempt,277.0,Exempt,1111,1111,1.0,11.0,NaN,NaN,NaN,1.0,11.0,NaN,NaN,NaN,2,2,6.0,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,2,2,2,1,2,2,25-34,25-34,No,No,1111,1111,1111,NaN,NaN,NaN,NaN,1111,NaN,NaN,NaN,6790,50.29,102000,247.0,2085,2374,20
6,2025,254900Y3KT6SZM11MQ06,99999,TX,48089.0,48089750300,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Joint,1,0,2,1,32,1,1111,1111,1111,755000,Exempt,Exempt,Exempt,2,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,1111,1111,1111,1111,Exempt,1,1,1111,1111,1,Exempt,206.0,Exempt,1111,1111,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2,2,5.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,2,1,2,2,2,65-74,65-74,Yes,Yes,1111,1111,1111,NaN,NaN,NaN,NaN,1111,NaN,NaN,NaN,4773,34.19,79400,120.0,1644,2989,33
7,2025,254900Y3KT6SZM11MQ06,26420,TX,48201.0,48201312603,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Male,2,0,2,1,31,1,1111,1111,1111,455000,Exempt,Exempt,Exempt,3,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,1111,1111,1111,1111,Exempt,1,1,1111,1111,1,Exempt,1386.0,Exempt,1111,1111,2.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,4,5.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,2,4,1,5,2,4,45-54,9999,No,NaN,1111,1111,1111,NaN,NaN,NaN,NaN,1111,NaN,NaN,NaN,3082,64.15,102000,71.0,642,1536,18
8,2025,254900Y3KT6SZM11MQ06,41700,TX,48029.0,48029121204,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Male,1,0,2,1,32,1,1111,1111,1111,315000,Exempt,Exempt,Exempt,2,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,1111,1111,1111,1111,Exempt,1,1,1111,1111,1,Exempt,269.0,Exempt,1111,1111,2.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,4,5.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,2,4,1,5,2,4,45-54,9999,No,NaN,1111,1111,1111,NaN,NaN,NaN,NaN,1111,NaN,NaN,NaN,8569,71.78,98300,55.0,1119,1739,41
9,2025,254900Y3KT6SZM11MQ06,19124,TX,48121.0,48121020126,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Joint,1,0,2,1,32,1,1111,1111,1111,245000,Exempt,Exempt,Exempt,3,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,Exempt,1111,1111,1111,1111,Exempt,1,3,1111,1111,1,Exempt,194.0,Exempt,1111,1111,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2,2,5.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,2,1,2,2,2,25-34,35-44,No,No,1111,1111,1111,NaN,NaN,NaN,NaN,1111,NaN,NaN,NaN,3779,58.35,117300,108.0,911,1134,15

In [ ]:
target_column = "action_taken"

# ratio of null values to filled values, higher null percentage means that most of the values are null values
pd.set_option("display.max_rows", None)

null_df = ((df.isnull().sum() / len(df)) * 100).to_frame()
null_df.columns = ["null_percentage"]
temp = null_df[null_df["null_percentage"]>=0].sort_values(by="null_percentage", ascending=False)
display(temp)

pd.reset_option("display.max_rows")

# print("        Null percentages       ")
# print("-------------------------------")
# for col, num in temp.iterrows():
#   print(f" {num['null_percentage']:.4f}% | {col}")

                                          null_percentage
co_applicant_ethnicity_5                        99.999188
co_applicant_ethnicity_4                        99.998819
applicant_ethnicity_5                           99.998081
applicant_ethnicity_4                           99.996310
co_applicant_race_5                             99.991365
co_applicant_race_4                             99.979187
applicant_race_5                                99.977268
co_applicant_ethnicity_3                        99.959481
applicant_race_4                                99.938373
applicant_ethnicity_3                           99.883462
denial_reason_4                                 99.872539
co_applicant_race_3                             99.856967
applicant_race_3                                99.598945
aus_5                                           99.396795
denial_reason_3                                 99.349338
aus_4                                           99.305277
aus_3                                           98.335484
co_applicant_race_2                             98.130159
co_applicant_ethnicity_2                        97.772871
multifamily_affordable_units                    97.383477
total_points_and_fees                           97.031798
denial_reason_2                                 96.475827
applicant_race_2                                95.182253
prepayment_penalty_term                         94.622002
aus_2                                           94.564508
applicant_ethnicity_2                           94.046990
lender_credits                                  82.592876
intro_rate_period                               78.482399
discount_points                                 74.877189
co_applicant_age_above_62                       64.783885
total_loan_costs                                52.362635
origination_charges                             51.847700
rate_spread                                     50.367178
debt_to_income_ratio                            35.627354
combined_loan_to_value_ratio                    34.811739
interest_rate                                   33.498385
property_value                                  20.591869
income                                          16.137905
applicant_age_above_62                          13.474074
census_tract                                     2.643609
county_code                                      2.233550
state_code                                       1.265676
loan_term                                        1.182867
conforming_loan_limit                            0.419801
applicant_ethnicity_1                            0.032695
applicant_race_1                                 0.023027
co_applicant_ethnicity_1                         0.011218
co_applicant_race_1                              0.007676
business_or_commercial_purpose                   0.000000
open_end_line_of_credit                          0.000000
hoepa_status                                     0.000000
derived_loan_product_type                        0.000000
activity_year                                    0.000000
lei                                              0.000000
derived_msa_md                                   0.000000
loan_amount                                      0.000000
derived_dwelling_category                        0.000000
derived_ethnicity                                0.000000
derived_race                                     0.000000
derived_sex                                      0.000000
action_taken                                     0.000000
purchaser_type                                   0.000000
preapproval                                      0.000000
loan_type                                        0.000000
loan_purpose                                     0.000000
lien_status                                      0.000000
reverse_mortgage                                 0.000000
negative_amortization                            0.000000
applicant_ethnicity_observed                     0.000000
occupancy_type                                   0.000000
construction_method                              0.000000
co_applicant_ethnicity_observed                  0.000000
total_units                                      0.000000
balloon_payment                                  0.000000
interest_only_payment                            0.000000
manufactured_home_land_property_interest         0.000000
manufactured_home_secured_property_type          0.000000
co_applicant_credit_score_type                   0.000000
applicant_credit_score_type                      0.000000
other_nonamortizing_features                     0.000000
co_applicant_sex                                 0.000000
applicant_race_observed                          0.000000
co_applicant_race_observed                       0.000000
initially_payable_to_institution                 0.000000
submission_of_application                        0.000000
applicant_age                                    0.000000
co_applicant_age                                 0.000000
co_applicant_sex_observed                        0.000000
applicant_sex_observed                           0.000000
applicant_sex                                    0.000000
aus_1                                            0.000000
denial_reason_1                                  0.000000
tract_population                                 0.000000
tract_minority_population_percent                0.000000
ffiec_msa_md_median_family_income                0.000000
tract_to_msa_income_percentage                   0.000000
tract_owner_occupied_units                       0.000000
tract_one_to_four_family_homes                   0.000000
tract_median_age_of_housing_units                0.000000

In [ ]:
# checking duplicates
# not too sure how to check this one
numDupes = df.duplicated().sum()
print(f"Number of duplicate entries: {numDupes}")

Number of duplicate entries: 649

In [ ]:
# this was just for copypasting the string names in the next cell
for col, dtype in df.dtypes.items():
  # print(f"{col}: {dtype}")
  print(f"\"{col}\",")

"activity_year",
"lei",
"derived_msa_md",
"state_code",
"county_code",
"census_tract",
"conforming_loan_limit",
"derived_loan_product_type",
"derived_dwelling_category",
"derived_ethnicity",
"derived_race",
"derived_sex",
"action_taken",
"purchaser_type",
"preapproval",
"loan_type",
"loan_purpose",
"lien_status",
"reverse_mortgage",
"open_end_line_of_credit",
"business_or_commercial_purpose",
"loan_amount",
"combined_loan_to_value_ratio",
"interest_rate",
"rate_spread",
"hoepa_status",
"total_loan_costs",
"total_points_and_fees",
"origination_charges",
"discount_points",
"lender_credits",
"loan_term",
"prepayment_penalty_term",
"intro_rate_period",
"negative_amortization",
"interest_only_payment",
"balloon_payment",
"other_nonamortizing_features",
"property_value",
"construction_method",
"occupancy_type",
"manufactured_home_secured_property_type",
"manufactured_home_land_property_interest",
"total_units",
"multifamily_affordable_units",
"income",
"debt_to_income_ratio",
"applicant_credit_score_type",
"co_applicant_credit_score_type",
"applicant_ethnicity_1",
"applicant_ethnicity_2",
"applicant_ethnicity_3",
"applicant_ethnicity_4",
"applicant_ethnicity_5",
"co_applicant_ethnicity_1",
"co_applicant_ethnicity_2",
"co_applicant_ethnicity_3",
"co_applicant_ethnicity_4",
"co_applicant_ethnicity_5",
"applicant_ethnicity_observed",
"co_applicant_ethnicity_observed",
"applicant_race_1",
"applicant_race_2",
"applicant_race_3",
"applicant_race_4",
"applicant_race_5",
"co_applicant_race_1",
"co_applicant_race_2",
"co_applicant_race_3",
"co_applicant_race_4",
"co_applicant_race_5",
"applicant_race_observed",
"co_applicant_race_observed",
"applicant_sex",
"co_applicant_sex",
"applicant_sex_observed",
"co_applicant_sex_observed",
"applicant_age",
"co_applicant_age",
"applicant_age_above_62",
"co_applicant_age_above_62",
"submission_of_application",
"initially_payable_to_institution",
"aus_1",
"aus_2",
"aus_3",
"aus_4",
"aus_5",
"denial_reason_1",
"denial_reason_2",
"denial_reason_3",
"denial_reason_4",
"tract_population",
"tract_minority_population_percent",
"ffiec_msa_md_median_family_income",
"tract_to_msa_income_percentage",
"tract_owner_occupied_units",
"tract_one_to_four_family_homes",
"tract_median_age_of_housing_units",

In [ ]:
# Data preprocessing

# removing unnecessary features, add more or remove if need be
features_to_drop = [
    "lei",
    "activity_year",
    "applicant_ethnicity_1",
    "applicant_ethnicity_2",
    "applicant_ethnicity_3",
    "applicant_ethnicity_4",
    "applicant_ethnicity_5",
    "co_applicant_ethnicity_1",
    "co_applicant_ethnicity_2",
    "co_applicant_ethnicity_3",
    "co_applicant_ethnicity_4",
    "co_applicant_ethnicity_5",
    "applicant_ethnicity_observed",
    "co_applicant_ethnicity_observed",
    "applicant_race_1",
    "applicant_race_2",
    "applicant_race_3",
    "applicant_race_4",
    "applicant_race_5",
    "co_applicant_race_1",
    "co_applicant_race_2",
    "co_applicant_race_3",
    "co_applicant_race_4",
    "co_applicant_race_5",
    "aus_1",
    "aus_2",
    "aus_3",
    "aus_4",
    "aus_5",
    "denial_reason_1",
    "denial_reason_2",
    "denial_reason_3",
]

# df.drop(columns=features_to_drop)

# Drop or fill in null values with median/averages

# Perform feature selection (filter, wrapper, etc.) if still too many features

# Scale features

# Apply SMOTE because dataset is heavily biased towards loan approval